### ISSUE TITLE
Compilation with Qhull fails

### ISSUE THREAD

**Issue by JensWehner** [hpgem/hpgem#25]
`/home/jens/Programs/hpgem/applications/UnstructuredMeshDemo/app1.cpp:25:10: fatal error: Base/ElementCacheData.h: No such file or directory
 #include "Base/ElementCacheData.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
`
The problematic commit seems to be https://github.com/hpgem/hpgem/commit/25c12d984e4c272ac051263003d48814c777d5a7

**Comment by Laar** [comment]
Fixed by removing qhull
