### ISSUE TITLE
Installation with PETSc and SLEPc

### ISSUE THREAD

**Issue by NicoRenaud** [hpgem/hpgem#6]
Hi there, 

Installing hpGEMM without PETSc and SLEPc works like a charm. However trying to link with PETSc and SLEPc leads to quite some issues. I saw that Laars had opened an issue here https://github.com/jedbrown/cmake-modules/issues/31 about it as well.

First I compiled PETSc and SLEPc from source. All the checks of both codes passed and I happily played with SLEPc. When trying to link hpGEM PETSc cannot be found. 

I then installed the conda packages of petsc and slepc. After checking that I can compile and run slepc examples, i tried to link hpGEM with them. While the libraryies were found, the tests of petsc and slepc that are performed during the configuration as part of the FindPackage failed.

Did you encounter such issue ?

**Comment by Laar** [comment]
The issue of not being able to run the test scripts is something that I have seen in three situations:
 - When using a different compiler for compiling hpGEM from PETSc & SLEPc. The latter probably use mpicxx and mpicc. So it may be necessary instruct cmake to use those compilers. The selected compilers should be somewhere in the cmake output from hpGEM.
 - After updating the system with a self compiled PETSc & SLEPc
 - With a PETSc & SLEPc compiled for the cluster nodes.

For configuring hpGEM to use PETSc and SLEPc I use the following settings
 - As environment variables I set `PETSC_DIR`, `SLEPC_DIR` and `PETSC_ARCH` (though the latter might not be needed if you install PETSc using the package manager).
 - When configuring hpGEM with cmake I pass as flags `-DhpGEM_USE_MPI=on`, `-DhpGEM_USE_SLEPC=on` and either  `-DhpGEM_USE_PETSC=on` or `-DhpGEM_USE_COMPLEX_PETSC=on` depending on what I need and how PETSc is compiled.

For working with Maxwell problems you need a version of PETSc that supports complex numbers. Which probably requires compiling it yourself. To configure PETSc for my colleagues I usually use the following command
```
./configure --with-scalar-type=complex \
    --download-fblaslapack \
    --download-scalapack \
    --download-mumps \
     --download-metis \
     --download-parmetis
```
This also includes METIS, which hpGEM can use for partitioning meshes.

**Comment by NicoRenaud** [comment]
Thanks for the info ! Some of the compilers set by my package manager seems to cause trouble. I'll start from a clean environment and I think it should be better.

**Comment by Laar** [comment]
Good to hear. One thing I noticed, apparently I sometimes also need to add `-DPETSC_ARCH=[....]` to the cmake flags.

**Comment by NicoRenaud** [comment]
you need the `-DPETSC_ARCH` flag because of that line no ? : https://github.com/hpgem/hpgem/blob/master/conf/cmake/ConfigureOptionalDependencies.cmake#l30

I also add to specify explicitly the cxx compiler in my case `-DCMAKE_CXX_COMPILER=mpic++` otherwise the multipass tests of petsc were failing. 

But it seems to be working now !

**Comment by Laar** [comment]
> you need the `-DPETSC_ARCH` flag because of that line no ? : https://github.com/hpgem/hpgem/blob/master/conf/cmake/ConfigureOptionalDependencies.cmake#L30

That could well be the case, but for me it really depends. On the cluster it works with just PETSC_ARCH as environment variable while in clion on macOS I do need to specify it. 

> I also add to specify explicitly the cxx compiler in my case `-DCMAKE_CXX_COMPILER=mpic++` otherwise the multipass tests of petsc were failing.
> 
> But it seems to be working now !

Great!

**Comment by JensWehner** [comment]
I think this is mostly accomplished via https://github.com/hpgem/hpgem/pull/22
