### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by NicoRenaud** [hpgem/hpgem#7]
It would be great to have a series of small test ran at each push or at least each PR. There are a few options available. The two that we generally prefer are Travis and  Github actions. That would also allows us to have an estimate of the code coverage.  

For larger tests we are also experimenting with deploying CI on the HPC cloud of Surf. We could deploy that for hpgem as well if you want

@Laar, what are your thoughts on that ?

**Comment by Laar** [comment]
I had some past experience with Travis (though 5+ years ago) and nothing with Github actions. As I'm quite out of the loop about the capabilities and limitations of both, so I can't judge whether one of them is better than the other at the moment.

For more practical concerns, we have quite a few tests (thanks to @Freekjan). There are quite a few tests that are roughly of the unit test/small integration test size, and also several full scale tests more looking like acceptance tests. Most of these can function without PETSc and run quite fast (<1s), though several of the larger acceptance tests can take several minutes. Running these tests is as simple as `make test`, but they are not using any testing framework or similar that would allow easy separation of the several tests into groups.

If we want to run the tests with PETSc, the question will be if that needs to be compiled every time and whether the chosen service can do that. Alternatively it may be better to use the facilities of Surf for this.

**Comment by JensWehner** [comment]
I think this large issue is done via https://github.com/hpgem/hpgem/pull/32
